FROM java:alpine

RUN apk add --no-cache curl
RUN curl -o /sonar-scanner-cli.zip -OL https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778.zip
RUN unzip sonar-scanner-cli.zip
RUN mv sonar-scanner-3.0.3.778 sonar-scanner
RUN cd /usr/bin && ln -s /sonar-scanner/bin/sonar-scanner sonar-scanner
RUN rm -rf /sonar-scanner-cli.zip
RUN apk del curl
WORKDIR /app
CMD ['/sonar-scaner/bin/sonar-scanner']
